// Ukrainian - english pairs of region names
export const REGIONS_MAP = {
  Krym: 'Крим',
  Vinnytska: 'Вінницька',
  Volynska: 'Волинська',
  Dnipropetrovska: 'Дніпропетровська',
  Donetska: 'Донецька',
  Zhytomyrska: 'Житомирська',
  Zakarpatska: 'Закарпатська',
  Zaporizka: 'Запорізька',
  Ivano_Frankivska: 'Івано-Франківська',
  Kyivska: 'Київська',
  Kyiv: 'Київ',
  Kirovohradska: 'Кіровоградська',
  Luhanska: 'Луганська',
  Lvivska: 'Львівська',
  Mykolaivska: 'Миколаївська',
  Odeska: 'Одеська',
  Poltavska: 'Полтавська',
  Rivnenska: 'Рівненська',
  Sumska: 'Сумська',
  Ternopilska: 'Тернопільська',
  Kharkivska: 'Харківська',
  Khersonska: 'Херсонська',
  Khmelnytska: 'Хмельницька',
  Cherkaska: 'Черкаська',
  Chernivetska: 'Чернівецька',
  Chernihivska: 'Чернігівська',
  Sevastopol: 'Севастополь',
} as const;
